id: P000020
initial_creation_type: ebook
created_at: 31/01/2020
last_modified_at: 26/11/2021
source_metadata:
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  authors:
  - མཛད་པ་པོ། མཁན་པོ་བློ་གྲོས་དོན་ཡོད།
  id: RDI-SS-18
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
web_metadata:
  title:
    en: The Lapis Lazuli Jewel That Reveals What Is Hidden in “The Jewel Ornament
      of Liberation:The Wish-Fulfilling Gem of the Noble Teachings”
    bo: དམ་ཆོས་ཡིད་བཞིན་ནོར་བུ་ཐར་པ་རིན་པོ་ཆེའི་རྒྱན་གྱི་གབ་པ་མངོན་དུ་ཕྱུང་བ་བཻཌཱུརྱ་ཡི་ཕྲ་ཚོམ།
  collection:
    en: RDI Study Series–  Book 18
    bo: ཐོས་བསམ་འཆད་ཉན་གྱི་རིམ་པ།–  དེབ། ༡༨
  author:
    en: Khenpo Lodro Donyo
    bo: མཁན་པོ་བློ་གྲོས་དོན་ཡོད།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-SS-18
  category:
    en: Stages of the Path
    bo: ལམ་རིམ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-SS-18.epub
  description:
    en: ''
    bo: ''
